-- 006: Weekly review summaries generated by the AI coach during check-ins

CREATE TABLE weekly_reviews (
  id            UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id       UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  week_start    DATE NOT NULL,             -- Monday of the reviewed week (ISO)
  summary_html  TEXT,                      -- Short AI-generated HTML narrative
  kpi_delta     JSONB,                     -- Key metric deltas vs prior week
  created_at    TIMESTAMPTZ DEFAULT now(),
  updated_at    TIMESTAMPTZ DEFAULT now(),
  UNIQUE(user_id, week_start)
);

ALTER TABLE weekly_reviews ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users manage own weekly reviews"
  ON weekly_reviews FOR ALL
  USING  (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE INDEX weekly_reviews_user_week ON weekly_reviews (user_id, week_start DESC);
